import Head from "next/head";
import { useState } from "react";
import { useBarMan } from "~/store/store";
import BarManWrapper from "./components/form/barman/barManWrapper";

const BarMan = () => {
  const {scan,setScan}=useBarMan()
    return (<>
    <Head>
        <title>Ice cream | bar man</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" w-full h-screen flex flex-col">
        {scan&&<div className="w-full max-w-md h-full   min-h-screen mx-auto md:border-2 border-zinc-200 px-4 pt-2 ">
            

       <BarManWrapper/>
        </div>}
        {!scan&&<div className="my-auto  flex">
        <button  onClick={()=>setScan(true)}  className="mx-auto bg-white w-full max-w-md h-12   md:border-2  px-4 pt-2  border border-gray-600 mt-5  max-w-96 text-2xl hover:scale-105 active:scale-95 transition-all duration-150 ease-in-out disabled:cursor-not-allowed text-black">Scan</button>

        </div>}
      </main>
    </>  );
}
 
export default BarMan;