import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

//import { api } from "~/utils/api";
import InitialLogo from "./components/initialLogo";
import {motion} from 'framer-motion'
import { useEffect, useState } from "react";
import FormWrapper from "./components/form/formWrapper";
import UserWrapper from "./components/form/user/userWrapper";
const Home: NextPage = () => {
//  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // to show the svg at initial render
  const [isLoading,setIsLoading]=useState(true)
  useEffect(() => {
    const timer = setTimeout(() => {
      // set the loader state to false
        setIsLoading(false)
    }, 2500);

    return () => clearTimeout(timer);
  }, []);


  

  return (
    <>
      <Head>
        <title>Ice cream | home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="break-words  min-h-screen flex" >
        {isLoading&&<motion.div animate={{scale:0, opacity:0}} transition={{delay:1.5,duration:1}} className="max-w-96  h-auto m-auto">
         <InitialLogo/>
        </motion.div>
}
        {!isLoading&&<div className="w-full max-w-md h-full min-h-screen mx-auto md:border-2 border-zinc-200 px-4 pt-2 ">
              <UserWrapper/>
        </div>}

      </main>
    </>
  );
};

export default Home;


